### ISSUE TITLE
Document the globalReact option

### ISSUE THREAD

**Issue by DylanPiercey** [pugjs/react-jade#30]
At the end of a template function, it is invoked with this

``` JavaScript
(typeof React !== "undefined" ? React : require("../../node_modules/react/react.js")));
```

Which in-lines react. This is a problem for me since react is in an external bundle.

Is there a away around this?

**Comment by ForbesLindesay** [comment]
Hi, I'm sorry I didn't manage to resolve this issue.  I've now replaced this project with https://github.com/pugjs/babel-plugin-transform-react-pug so I won't be looking at any of these outstanding issues.
