### ISSUE TITLE
`if` can break elements that follow it

### ISSUE THREAD

**Issue by emilis** [pugjs/react-jade#34]
Consider the following:

``` jade
.container

    if this.state.records.length > 10
        .row
            p This is shown only after more than 10 records are loaded

    .row
        each record in this.state.records
            RecordView( key= record.id, record= record )
```

The RecordViews will be re-created and lose state once `this.state.records` array will grow beyond 10 items.

I was told on _#reactjs_ IRC that `if` and second `.row` should be passed as separate arguments to `React.createElement()` for `.container`. Similar to this:

``` javascript
> echo '<div>{a && <h1 />}{[].map(x => <p />)}</div>' | ./webapp/node_modules/node-jsx/node_modules/.bin/jsx --harmony
built Module("<stdin>")
React.createElement("div", null,
    a && React.createElement("h1", null),
    [].map(function(x)  {return React.createElement("p", null);})
)
```

_Taken from https://www.refheap.com/97072._

My current workaround is to add keys to all `.row` elements like this:

``` jade
.container

    if this.state.records.length > 10
        .row( key= "first" )
            p This is shown only after more than 10 records are loaded

    .row( key= "second" )
        each record in this.state.records
```

**Comment by emilis** [comment]
This could be related to #11 .

**Comment by ForbesLindesay** [comment]
This is a really tricky thing to try and deal with.  One option would be to revert to using an array inside `if` like we do with `each`.  You would still have to add the key, but at least react would warn you that you needed a key.  On the other hand, it would force you to add a lot of keys where they might not really be needed.

Another option would be for us to attempt to auto-generate keys.  We could take the approach of making the body of any `if` block be an array (and adding an empty array as the default for else) but use the index as the default key.  One question, how does react handle arrays of arrays.  e.g.

```jade
each item in [0, 1, 2, 3, 4]
  if item % 2 === 0
    strong= item
```

which would end up as:

```js
React.createElement('div', {}, [
  [React.createElement('strong', {key: 0}, 0)],
  [],
  [React.createElement('strong', {key: 0}, 2)],
  [],
  [React.createElement('strong', {key: 0}, 4)]
]);

**Comment by ForbesLindesay** [comment]
Hi, I'm sorry I didn't manage to resolve this issue.  I've now replaced this project with https://github.com/pugjs/babel-plugin-transform-react-pug so I won't be looking at any of these outstanding issues.
