### ISSUE TITLE
Is it a necessity to wrap unescaped html into div?

### ISSUE THREAD

**Issue by KonanMentor** [pugjs/react-jade#60]
I am developing a universal(aka isomorphic) app. So I need to pass some initial data to client. As long as `react-jade` does not support interpolation I have to write something like this:

``` javascript
...
render: jade`
...
script!=scriptBody
`.locals({scriptBody: `window.__data__ = ${JSON.stringify(data)}`
```

But it renders to

``` html
<script><div>window.__data__ = data</div></script>
```

**Comment by KonanMentor** [comment]
Okay. I managed to do this with help of `dangerouslySetInnerHTML`. But anyway is it the right way to do this?

**Comment by ForbesLindesay** [comment]
Hi, I'm sorry I didn't manage to resolve this issue.  I've now replaced this project with https://github.com/pugjs/babel-plugin-transform-react-pug so I won't be looking at any of these outstanding issues.
