### ISSUE TITLE
Rename internal variable

### ISSUE THREAD

**Issue by KonanMentor** [pugjs/react-jade#61]
The following code will not work due to internal variable named `tags`

``` js
jade`
each tag, index in tags
...
`.locals({tags: [...]})
```

It should be replaced by some less commonly used name or at least documented.

**Comment by ForbesLindesay** [comment]
Hi, I'm sorry I didn't manage to resolve this issue.  I've now replaced this project with https://github.com/pugjs/babel-plugin-transform-react-pug so I won't be looking at any of these outstanding issues.
