### ISSUE TITLE
class syntax for render?

### ISSUE THREAD

**Issue by fengb** [pugjs/react-jade#62]
It is currently documented for ES6 to do the following

``` javascript
var TodoList = React.createClass({
  render: jade`
/* ... */
`
});
```

With React now supporting the standard **class** syntax, I'm not quite sure how to get `react-jade` to play nicely. My attempts are basically hacks:

``` javascript
class TodoList extends React.Component {
}

TodoList.prototype.render = jade`
/* ... */
`
```

Is there a clean way of using the class syntax?

**Comment by KonanMentor** [comment]
It seems that there is no clean way of using the class syntax for ES6.

But ES7 provides the following syntax
```js
class TodoList extends React.Component {
  render = jade`
}
```

**Comment by ForbesLindesay** [comment]
Hi, I'm sorry I didn't manage to resolve this issue.  I've now replaced this project with https://github.com/pugjs/babel-plugin-transform-react-pug so I won't be looking at any of these outstanding issues.
