### ISSUE TITLE
Using Gulp: 

### ISSUE THREAD

**Issue by Gooseware** [pugjs/react-jade#63]
I have tried to add the react-jade transform to my gulp config:

``` javascript
      // Required watchify args
      cache: {},
      packageCache: {},
      // full system file paths, disable for production
      fullPaths: true,
      // Add file extentions to make optional in your requires
      extensions: config.extensions,
      transforms: [reactJade,babelify],
      // Enable source maps
      debug: true
```

But for some reason when I try:

``` javascript
'use strict';

var React = require('react');
var jade = require('react-jade');
var log = require('loglevel');
var tpl = jade.compileFile(__dirname+'/hello.jade');

var HelloView = React.createClass({
  // es6 style method
//  render() {
//    return (
//      <h1>Hello World with React</h1>
//    );
//  }
    render: function(){
        return(tpl())
    }
});

module.exports = HelloView;
```

I get:

Uncaught TypeError: fs.readFileSync is not a function

Wondering if anyone would be able to help.... does anyone have an example gulp config which manages to get react-jade working.

**Comment by cloud-walker** [comment]
Maybe babelify should be before react-jade

**Comment by ForbesLindesay** [comment]
Either way you'll probalby run into problems.  I intend to re-write this module as a babel transfrom, but haven't yet had the time to do that.

**Comment by ForbesLindesay** [comment]
Hi, I'm sorry I didn't manage to resolve this issue.  I've now replaced this project with https://github.com/pugjs/babel-plugin-transform-react-pug so I won't be looking at any of these outstanding issues.
