### ISSUE TITLE
Great library, work with React Native?

### ISSUE THREAD

**Issue by ben-pr-p** [pugjs/react-jade#70]
I just finished using this library to build out my react components, but eventually deciding to rewrite all of my components in JSX so that it could be more easily ported to React Native.

I also just started working with a few more developers that have never used React before, so I thought porting it to JSX would make it look more like the example documentation they are likely to find online. 

Unfortunate choice that is sure to slow down my development speed and internal state of comfort, but will probably help the team.

Do you plan to include react native support in the future? What kind of task would that entail? Does compilation to react javascript imply react native support?

**Comment by ForbesLindesay** [comment]
Hi, I'm sorry I didn't manage to resolve this issue.  I've now replaced this project with https://github.com/pugjs/babel-plugin-transform-react-pug so I won't be looking at any of these outstanding issues.
