### ISSUE TITLE
Set className of root div if no single root div in jade file

### ISSUE THREAD

**Issue by mykone** [pugjs/react-jade#71]
Hello, just started to use this lib, and it's awesome so far. 

I have a feature request, can you create an attribute "className", when calling compileFile(), so we can provide a className to the outer <div/> in cases where there are no single element as root in jade templates?

**Comment by ForbesLindesay** [comment]
Hi, I'm sorry I didn't manage to resolve this issue.  I've now replaced this project with https://github.com/pugjs/babel-plugin-transform-react-pug so I won't be looking at any of these outstanding issues.
