### ISSUE TITLE
React 15 support

### ISSUE THREAD

**Issue by ai** [pugjs/react-jade#72]
React was updated and we need to update `dependencies`.

@ForbesLindesay

**Comment by ai** [comment]
@ForbesLindesay any updates? I can send this 1 line PR if it will help.

**Comment by dskvr** [comment]
@ForbesLindesay Feeling lucky with this bump :D

**Comment by ForbesLindesay** [comment]
Hi, I'm sorry I didn't manage to resolve this issue.  I've now replaced this project with https://github.com/pugjs/babel-plugin-transform-react-pug so I won't be looking at any of these outstanding issues.
