### ISSUE TITLE
 jade_join_classes is not defined

### ISSUE THREAD

**Issue by Spouark** [pugjs/react-jade#74]
I keep getting this error when i try to compile a jade file

``` javascript
var template = jade.compileFile(__dirname + '/../../templates/views/register.jade');
```

Using it with keystoneJs

**Comment by ForbesLindesay** [comment]
Hi, I'm sorry I didn't manage to resolve this issue.  I've now replaced this project with https://github.com/pugjs/babel-plugin-transform-react-pug so I won't be looking at any of these outstanding issues.
